# TEMPLATE CLASSES = LIST
class rduModem2(M.Document):
        cmac = M.StringField(required=True)
        access = M.StringField()
        chaddr = M.StringField()
        clientId = M.StringField()
        clientIdCreated = M.StringField()
        cos = M.StringField()
        deviceType = M.StringField()
        domain = M.StringField()
        dhcpMessageType = M.StringField()
        dhcpParamRequestList = M.StringField()
        dhcpCriteria = M.StringField()
        DIVISION = M.StringField()
        explanation = M.StringField()
        giaddr = M.StringField()
        hlen = M.StringField()
        htype = M.StringField()
        isBehindRequiredDevice = M.StringField()
        isProvisioned = M.StringField()
        isRegistered = M.StringField()
        isInRequiredPortGroup = M.StringField()
        oidRevNum = M.StringField()
        PACKAGE = M.StringField()
        provGroup = M.StringField()
        reason = M.StringField()
        relayAgentCircuitId = M.StringField()
        relayAgentRemoteId = M.StringField()
        relayAgentInfo = M.StringField()
        subscriberId = M.StringField()
        viVendorOpts = M.StringField()
        vendorEncapsulatedOptions = M.StringField()
        timestamp = M.StringField()
        pass
