{
    "GigabitEthernet1/1/18": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4249",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/19": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.424a",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/20": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.424b",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/21": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.424c",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/22": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.424d",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/23": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.424e",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/24": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.424f",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/25": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4250",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/26": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4251",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/27": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4252",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/28": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4253",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/29": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4254",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/30": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4255",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/31": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4256",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/32": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4257",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/33": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4258",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/34": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4259",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/35": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.425a",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/36": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.425b",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/37": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.425c",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/38": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.425d",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/39": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.425e",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/40": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.425f",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/41": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4260",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/42": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4261",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/43": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4262",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/44": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4263",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/45": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4264",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/46": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4265",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/47": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4266",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "GigabitEthernet1/1/48": {
        "mtu": 10200,
        "ipv4": {},
        "type": "GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "auto",
        "mediatype": "1G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4267",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/1": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "10Gbit",
        "mediatype": "10GE LR 10km (SFP+)",
        "macaddress": "609c.9fee.4269",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "10GigabitEthernet1/2/2": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.426a",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/3": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.426b",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/4": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.426c",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/5": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.426d",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/6": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.426e",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/7": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.426f",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "10GigabitEthernet1/2/8": {
        "mtu": 10200,
        "ipv4": {},
        "type": "10GigabitEthernet",
        "duplex": "unknown",
        "bandwidth": "10Gbit",
        "mediatype": "EMPTY",
        "macaddress": "609c.9fee.4270",
        "operstatus": "down",
        "description": null,
        "lineprotocol": "down "
    },
    "2.5GigabitEthernet1/1/1": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4238",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/2": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4239",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/3": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.423a",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/4": {
        "mtu": 10200,
        "ipv4": {
            "subnet": "24",
            "address": "192.168.0.166"
        },
        "ipv6": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4238",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/5": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.423c",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/6": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.423d",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/7": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.423e",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/8": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.423f",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/9": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4240",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/10": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4241",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/11": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4242",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/12": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4243",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/13": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4244",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/14": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4245",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/15": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4246",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    },
    "2.5GigabitEthernet1/1/16": {
        "mtu": 10200,
        "ipv4": {},
        "type": "2.5GigabitEthernet",
        "duplex": "fdx",
        "bandwidth": "auto",
        "mediatype": "2.5G M-C (Gig-Copper)",
        "macaddress": "609c.9fee.4247",
        "operstatus": "up",
        "description": null,
        "lineprotocol": "up "
    }
}
