linux:
  username: "ADMIN"
  private_key_file: "/opt/paramiko-test-key"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: linux
  prompt: "([@]+[a-zA-Z0-9\.\-\_\:\ \~\]]+[#$\ ]+[ ])"
  buffering: ""
juniper_junos:
  username: "ADMIN"
  private_key_file: "/opt/paramiko-test-key"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: juniper_junos
  prompt: "([@]+[a-zA-Z0-9\.\-\_]+[>#%]+[ ])"
  buffering: 'set cli screen-length 0'
ruckus:
  username: "admin"
  private_key_file: "/opt/gainspeed.txt"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: ruckus
  prompt: "([@]+[a-zA-Z0-9\.\-\_\ \(\)]+[>#%])"
  buffering: 'en,skip-page-display'
lx:
  username: "arcuser"
  private_key_file: "/opt/lx.arcuser.txt"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: mrvTS
  prompt: "([a-zA-Z0-9\-\_]+[0-9\:\ ]+[>])"
  buffering: 'no pause'
ndev:
  username: "ansible"
  private_key_file: "/opt/NetDev-key"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: juniper_junos
  prompt: "([@]+[a-zA-Z0-9\.\-\_]+[>#%]+[ ])"
  buffering: 'set cli screen-length 0'
commscope:
  username: "root"
  private_key_file: "/opt/commscope.txt"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: commscope
  prompt: "([a-zA-Z0-9\-\.\(\)\_]*[># ])"
  buffering: 'terminal length 0'  
gainspeed:
  username: "admin"
  private_key_file: "/opt/gainspeed.txt"
  ansible_ssh_common_args: '-okexalgorithms=+diffie-hellman-group1-sha1 '
  vendor: gainspeed
  prompt: "<show_config_|_match_prompt>"
  buffering: 'set paginate false'
